// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v5.29.3
// source: common.proto

/* eslint-disable */

export const protobufPackage = 'common';

export interface Pagination {
  page: number;
  pageSize: number;
}

export const COMMON_PACKAGE_NAME = 'common';
